Document: rn1host
Title: Debian rn1host Manual
Author: <insert document author here>
Abstract: This manual describes what rn1host is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rn1host/rn1host.sgml.gz

Format: postscript
Files: /usr/share/doc/rn1host/rn1host.ps.gz

Format: text
Files: /usr/share/doc/rn1host/rn1host.text.gz

Format: HTML
Index: /usr/share/doc/rn1host/html/index.html
Files: /usr/share/doc/rn1host/html/*.html
